language: python
python:
  - "3.7"

# command to install dependencies
install:
 - pip install pipenv
 - pipenv install --dev

after_success:
- pipenv install codecov --dev
- codecov
- coverage report -i
- coverage report -i --rcfile .coveragerc_todo

# command to run tests
script: make dev

